yarnPath: .yarn/releases/yarn-3.0.1.cjs

packageExtensions:
  "@chakra-ui/transition@*":
    dependencies:
        framer-motion: "*"
  "@chakra-ui/system@*":
    dependencies:
        "@emotion/styled": "*"
        "@emotion/react": "*"
  "@emotion/styled@*":
    dependencies:
        "@emotion/react": "*"
  "@chakra-ui/checkbox@*":
    dependencies:
        "framer-motion": "*"
  "cz-lerna-changelog@*":
    dependencies:
        "@lerna/project": "*"
  "babel-plugin-remove-graphql-queries@*":
    dependencies:
        "gatsby-core-utils": "*"